using UnityEngine;

/// <summary>
/// ^Μlut参
/// </summary>
public class RecycleMarble : MonoBehaviour
{
    /// <summary>
    /// ^Μu]计q
    /// </summary>
    public static int recycleMarbles;

    public GameManager gm;

    private void OnTriggerEnter(Collider other)
    {
        if (other.name.Contains("y[窟"))
        {
            other.gameObject.GetComponent<Rigidbody>().velocity = Vector3.zero;
            other.transform.position = new Vector3(0, 0, 100);

            // ^Μu]计q W[
            recycleMarbles++;
            // pG ^Μ计q 单 ┮Τu]计q ち传 寄よ^X
            if (recycleMarbles == ControlSystem.allMarbles) gm.SwitchTurn(false);
        }
    }
}
